export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import "../styles/global.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
